#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanDienThoai.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanDienThoai")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBienTheSanPham(BienTheSanPham instance);
    partial void UpdateBienTheSanPham(BienTheSanPham instance);
    partial void DeleteBienTheSanPham(BienTheSanPham instance);
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void UpdateChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void DeleteChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKho(Kho instance);
    partial void UpdateKho(Kho instance);
    partial void DeleteKho(Kho instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNhanvien(Nhanvien instance);
    partial void UpdateNhanvien(Nhanvien instance);
    partial void DeleteNhanvien(Nhanvien instance);
    partial void InsertPhieuNhap(PhieuNhap instance);
    partial void UpdatePhieuNhap(PhieuNhap instance);
    partial void DeletePhieuNhap(PhieuNhap instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertSanPhamTonKho(SanPhamTonKho instance);
    partial void UpdateSanPhamTonKho(SanPhamTonKho instance);
    partial void DeleteSanPhamTonKho(SanPhamTonKho instance);
    partial void InsertThongSoSanPham(ThongSoSanPham instance);
    partial void UpdateThongSoSanPham(ThongSoSanPham instance);
    partial void DeleteThongSoSanPham(ThongSoSanPham instance);
    partial void InsertThuongHieu(ThuongHieu instance);
    partial void UpdateThuongHieu(ThuongHieu instance);
    partial void DeleteThuongHieu(ThuongHieu instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyBanDienThoaiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BienTheSanPham> BienTheSanPhams
		{
			get
			{
				return this.GetTable<BienTheSanPham>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this.GetTable<ChiTietPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<Kho> Khos
		{
			get
			{
				return this.GetTable<Kho>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<Nhanvien> Nhanviens
		{
			get
			{
				return this.GetTable<Nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this.GetTable<PhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<SanPhamTonKho> SanPhamTonKhos
		{
			get
			{
				return this.GetTable<SanPhamTonKho>();
			}
		}
		
		public System.Data.Linq.Table<ThongSoSanPham> ThongSoSanPhams
		{
			get
			{
				return this.GetTable<ThongSoSanPham>();
			}
		}
		
		public System.Data.Linq.Table<ThuongHieu> ThuongHieus
		{
			get
			{
				return this.GetTable<ThuongHieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BienTheSanPham")]
	public partial class BienTheSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hinh_anh;
		
		private int _id_thong_so_san_pham;
		
		private int _id_san_pham;
		
		private decimal _gia_ban;
		
		private decimal _gia_nhap;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntitySet<ChiTietPhieuNhap> _ChiTietPhieuNhaps;
		
		private EntitySet<SanPhamTonKho> _SanPhamTonKhos;
		
		private EntityRef<SanPham> _SanPham;
		
		private EntityRef<ThongSoSanPham> _ThongSoSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Onid_thong_so_san_phamChanging(int value);
    partial void Onid_thong_so_san_phamChanged();
    partial void Onid_san_phamChanging(int value);
    partial void Onid_san_phamChanged();
    partial void Ongia_banChanging(decimal value);
    partial void Ongia_banChanged();
    partial void Ongia_nhapChanging(decimal value);
    partial void Ongia_nhapChanged();
    #endregion
		
		public BienTheSanPham()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._ChiTietPhieuNhaps = new EntitySet<ChiTietPhieuNhap>(new Action<ChiTietPhieuNhap>(this.attach_ChiTietPhieuNhaps), new Action<ChiTietPhieuNhap>(this.detach_ChiTietPhieuNhaps));
			this._SanPhamTonKhos = new EntitySet<SanPhamTonKho>(new Action<SanPhamTonKho>(this.attach_SanPhamTonKhos), new Action<SanPhamTonKho>(this.detach_SanPhamTonKhos));
			this._SanPham = default(EntityRef<SanPham>);
			this._ThongSoSanPham = default(EntityRef<ThongSoSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="VarChar(300)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thong_so_san_pham", DbType="Int NOT NULL")]
		public int id_thong_so_san_pham
		{
			get
			{
				return this._id_thong_so_san_pham;
			}
			set
			{
				if ((this._id_thong_so_san_pham != value))
				{
					if (this._ThongSoSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_thong_so_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_thong_so_san_pham = value;
					this.SendPropertyChanged("id_thong_so_san_pham");
					this.Onid_thong_so_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_san_pham", DbType="Int NOT NULL")]
		public int id_san_pham
		{
			get
			{
				return this._id_san_pham;
			}
			set
			{
				if ((this._id_san_pham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_san_pham = value;
					this.SendPropertyChanged("id_san_pham");
					this.Onid_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_ban", DbType="Money NOT NULL")]
		public decimal gia_ban
		{
			get
			{
				return this._gia_ban;
			}
			set
			{
				if ((this._gia_ban != value))
				{
					this.Ongia_banChanging(value);
					this.SendPropertyChanging();
					this._gia_ban = value;
					this.SendPropertyChanged("gia_ban");
					this.Ongia_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_nhap", DbType="Money NOT NULL")]
		public decimal gia_nhap
		{
			get
			{
				return this._gia_nhap;
			}
			set
			{
				if ((this._gia_nhap != value))
				{
					this.Ongia_nhapChanging(value);
					this.SendPropertyChanging();
					this._gia_nhap = value;
					this.SendPropertyChanged("gia_nhap");
					this.Ongia_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BienTheSanPham_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="id", OtherKey="id_bien_the_san_pham")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BienTheSanPham_ChiTietPhieuNhap", Storage="_ChiTietPhieuNhaps", ThisKey="id", OtherKey="id_bien_the_san_pham")]
		public EntitySet<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this._ChiTietPhieuNhaps;
			}
			set
			{
				this._ChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BienTheSanPham_SanPhamTonKho", Storage="_SanPhamTonKhos", ThisKey="id", OtherKey="id_bien_the_san_pham")]
		public EntitySet<SanPhamTonKho> SanPhamTonKhos
		{
			get
			{
				return this._SanPhamTonKhos;
			}
			set
			{
				this._SanPhamTonKhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_BienTheSanPham", Storage="_SanPham", ThisKey="id_san_pham", OtherKey="id", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.BienTheSanPhams.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.BienTheSanPhams.Add(this);
						this._id_san_pham = value.id;
					}
					else
					{
						this._id_san_pham = default(int);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongSoSanPham_BienTheSanPham", Storage="_ThongSoSanPham", ThisKey="id_thong_so_san_pham", OtherKey="id", IsForeignKey=true)]
		public ThongSoSanPham ThongSoSanPham
		{
			get
			{
				return this._ThongSoSanPham.Entity;
			}
			set
			{
				ThongSoSanPham previousValue = this._ThongSoSanPham.Entity;
				if (((previousValue != value) 
							|| (this._ThongSoSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongSoSanPham.Entity = null;
						previousValue.BienTheSanPhams.Remove(this);
					}
					this._ThongSoSanPham.Entity = value;
					if ((value != null))
					{
						value.BienTheSanPhams.Add(this);
						this._id_thong_so_san_pham = value.id;
					}
					else
					{
						this._id_thong_so_san_pham = default(int);
					}
					this.SendPropertyChanged("ThongSoSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BienTheSanPham = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.BienTheSanPham = null;
		}
		
		private void attach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.BienTheSanPham = this;
		}
		
		private void detach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.BienTheSanPham = null;
		}
		
		private void attach_SanPhamTonKhos(SanPhamTonKho entity)
		{
			this.SendPropertyChanging();
			entity.BienTheSanPham = this;
		}
		
		private void detach_SanPhamTonKhos(SanPhamTonKho entity)
		{
			this.SendPropertyChanging();
			entity.BienTheSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoa_don;
		
		private int _id_bien_the_san_pham;
		
		private int _so_luong;
		
		private EntityRef<BienTheSanPham> _BienTheSanPham;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoa_donChanging(int value);
    partial void Onid_hoa_donChanged();
    partial void Onid_bien_the_san_phamChanging(int value);
    partial void Onid_bien_the_san_phamChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._BienTheSanPham = default(EntityRef<BienTheSanPham>);
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoa_don", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hoa_don
		{
			get
			{
				return this._id_hoa_don;
			}
			set
			{
				if ((this._id_hoa_don != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._id_hoa_don = value;
					this.SendPropertyChanged("id_hoa_don");
					this.Onid_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_bien_the_san_pham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_bien_the_san_pham
		{
			get
			{
				return this._id_bien_the_san_pham;
			}
			set
			{
				if ((this._id_bien_the_san_pham != value))
				{
					if (this._BienTheSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_bien_the_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_bien_the_san_pham = value;
					this.SendPropertyChanged("id_bien_the_san_pham");
					this.Onid_bien_the_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BienTheSanPham_ChiTietHoaDon", Storage="_BienTheSanPham", ThisKey="id_bien_the_san_pham", OtherKey="id", IsForeignKey=true)]
		public BienTheSanPham BienTheSanPham
		{
			get
			{
				return this._BienTheSanPham.Entity;
			}
			set
			{
				BienTheSanPham previousValue = this._BienTheSanPham.Entity;
				if (((previousValue != value) 
							|| (this._BienTheSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BienTheSanPham.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._BienTheSanPham.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._id_bien_the_san_pham = value.id;
					}
					else
					{
						this._id_bien_the_san_pham = default(int);
					}
					this.SendPropertyChanged("BienTheSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_HoaDon", ThisKey="id_hoa_don", OtherKey="id", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._id_hoa_don = value.id;
					}
					else
					{
						this._id_hoa_don = default(int);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuNhap")]
	public partial class ChiTietPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_phieu_nhap;
		
		private int _id_bien_the_san_pham;
		
		private int _so_luong;
		
		private EntityRef<BienTheSanPham> _BienTheSanPham;
		
		private EntityRef<PhieuNhap> _PhieuNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieu_nhapChanging(int value);
    partial void Onid_phieu_nhapChanged();
    partial void Onid_bien_the_san_phamChanging(int value);
    partial void Onid_bien_the_san_phamChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    #endregion
		
		public ChiTietPhieuNhap()
		{
			this._BienTheSanPham = default(EntityRef<BienTheSanPham>);
			this._PhieuNhap = default(EntityRef<PhieuNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieu_nhap", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_phieu_nhap
		{
			get
			{
				return this._id_phieu_nhap;
			}
			set
			{
				if ((this._id_phieu_nhap != value))
				{
					if (this._PhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_phieu_nhapChanging(value);
					this.SendPropertyChanging();
					this._id_phieu_nhap = value;
					this.SendPropertyChanged("id_phieu_nhap");
					this.Onid_phieu_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_bien_the_san_pham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_bien_the_san_pham
		{
			get
			{
				return this._id_bien_the_san_pham;
			}
			set
			{
				if ((this._id_bien_the_san_pham != value))
				{
					if (this._BienTheSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_bien_the_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_bien_the_san_pham = value;
					this.SendPropertyChanged("id_bien_the_san_pham");
					this.Onid_bien_the_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BienTheSanPham_ChiTietPhieuNhap", Storage="_BienTheSanPham", ThisKey="id_bien_the_san_pham", OtherKey="id", IsForeignKey=true)]
		public BienTheSanPham BienTheSanPham
		{
			get
			{
				return this._BienTheSanPham.Entity;
			}
			set
			{
				BienTheSanPham previousValue = this._BienTheSanPham.Entity;
				if (((previousValue != value) 
							|| (this._BienTheSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BienTheSanPham.Entity = null;
						previousValue.ChiTietPhieuNhaps.Remove(this);
					}
					this._BienTheSanPham.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhaps.Add(this);
						this._id_bien_the_san_pham = value.id;
					}
					else
					{
						this._id_bien_the_san_pham = default(int);
					}
					this.SendPropertyChanged("BienTheSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_ChiTietPhieuNhap", Storage="_PhieuNhap", ThisKey="id_phieu_nhap", OtherKey="id", IsForeignKey=true)]
		public PhieuNhap PhieuNhap
		{
			get
			{
				return this._PhieuNhap.Entity;
			}
			set
			{
				PhieuNhap previousValue = this._PhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhap.Entity = null;
						previousValue.ChiTietPhieuNhaps.Remove(this);
					}
					this._PhieuNhap.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhaps.Add(this);
						this._id_phieu_nhap = value.id;
					}
					else
					{
						this._id_phieu_nhap = default(int);
					}
					this.SendPropertyChanged("PhieuNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_khach_hang;
		
		private int _id_nhan_vien;
		
		private System.DateTime _ngay_tao_phieu;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<Nhanvien> _Nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_khach_hangChanging(int value);
    partial void Onid_khach_hangChanged();
    partial void Onid_nhan_vienChanging(int value);
    partial void Onid_nhan_vienChanged();
    partial void Onngay_tao_phieuChanging(System.DateTime value);
    partial void Onngay_tao_phieuChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._Nhanvien = default(EntityRef<Nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", DbType="Int NOT NULL")]
		public int id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					if ((this._KhachHang.HasLoadedOrAssignedValue || this._Nhanvien.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="Int NOT NULL")]
		public int id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					this.Onid_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_nhan_vien = value;
					this.SendPropertyChanged("id_nhan_vien");
					this.Onid_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao_phieu", DbType="Date NOT NULL")]
		public System.DateTime ngay_tao_phieu
		{
			get
			{
				return this._ngay_tao_phieu;
			}
			set
			{
				if ((this._ngay_tao_phieu != value))
				{
					this.Onngay_tao_phieuChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao_phieu = value;
					this.SendPropertyChanged("ngay_tao_phieu");
					this.Onngay_tao_phieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="id", OtherKey="id_hoa_don")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="id_khach_hang", OtherKey="id", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._id_khach_hang = value.id;
					}
					else
					{
						this._id_khach_hang = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_HoaDon", Storage="_Nhanvien", ThisKey="id_khach_hang", OtherKey="id", IsForeignKey=true)]
		public Nhanvien Nhanvien
		{
			get
			{
				return this._Nhanvien.Entity;
			}
			set
			{
				Nhanvien previousValue = this._Nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._Nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhanvien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._Nhanvien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._id_khach_hang = value.id;
					}
					else
					{
						this._id_khach_hang = default(int);
					}
					this.SendPropertyChanged("Nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _sdt;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _hinh_anh;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(300)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="VarChar(300)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="id", OtherKey="id_khach_hang")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kho")]
	public partial class Kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _dia_chi;
		
		private EntitySet<SanPhamTonKho> _SanPhamTonKhos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    #endregion
		
		public Kho()
		{
			this._SanPhamTonKhos = new EntitySet<SanPhamTonKho>(new Action<SanPhamTonKho>(this.attach_SanPhamTonKhos), new Action<SanPhamTonKho>(this.detach_SanPhamTonKhos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(300)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(300)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_SanPhamTonKho", Storage="_SanPhamTonKhos", ThisKey="id", OtherKey="id_kho")]
		public EntitySet<SanPhamTonKho> SanPhamTonKhos
		{
			get
			{
				return this._SanPhamTonKhos;
			}
			set
			{
				this._SanPhamTonKhos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhamTonKhos(SanPhamTonKho entity)
		{
			this.SendPropertyChanging();
			entity.Kho = this;
		}
		
		private void detach_SanPhamTonKhos(SanPhamTonKho entity)
		{
			this.SendPropertyChanging();
			entity.Kho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _sdt;
		
		private string _diachi;
		
		private string _ma_thue;
		
		private EntitySet<PhieuNhap> _PhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void Onma_thueChanging(string value);
    partial void Onma_thueChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._PhieuNhaps = new EntitySet<PhieuNhap>(new Action<PhieuNhap>(this.attach_PhieuNhaps), new Action<PhieuNhap>(this.detach_PhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(300)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(300)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(300)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_thue", DbType="VarChar(300)")]
		public string ma_thue
		{
			get
			{
				return this._ma_thue;
			}
			set
			{
				if ((this._ma_thue != value))
				{
					this.Onma_thueChanging(value);
					this.SendPropertyChanging();
					this._ma_thue = value;
					this.SendPropertyChanged("ma_thue");
					this.Onma_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_PhieuNhap", Storage="_PhieuNhaps", ThisKey="id", OtherKey="id_nha_cung_cap")]
		public EntitySet<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this._PhieuNhaps;
			}
			set
			{
				this._PhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuNhaps(PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_PhieuNhaps(PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhanvien")]
	public partial class Nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _sdt;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _quyen_han;
		
		private string _hinh_anh;
		
		private string _usernane;
		
		private string _password;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Onquyen_hanChanging(string value);
    partial void Onquyen_hanChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void OnusernaneChanging(string value);
    partial void OnusernaneChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Nhanvien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen_han", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string quyen_han
		{
			get
			{
				return this._quyen_han;
			}
			set
			{
				if ((this._quyen_han != value))
				{
					this.Onquyen_hanChanging(value);
					this.SendPropertyChanging();
					this._quyen_han = value;
					this.SendPropertyChanged("quyen_han");
					this.Onquyen_hanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="VarChar(300)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usernane", DbType="VarChar(300)")]
		public string usernane
		{
			get
			{
				return this._usernane;
			}
			set
			{
				if ((this._usernane != value))
				{
					this.OnusernaneChanging(value);
					this.SendPropertyChanging();
					this._usernane = value;
					this.SendPropertyChanged("usernane");
					this.OnusernaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(300)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_HoaDon", Storage="_HoaDons", ThisKey="id", OtherKey="id_khach_hang")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhap")]
	public partial class PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_nha_cung_cap;
		
		private System.DateTime _ngay_tao_phieu;
		
		private EntitySet<ChiTietPhieuNhap> _ChiTietPhieuNhaps;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_nha_cung_capChanging(int value);
    partial void Onid_nha_cung_capChanged();
    partial void Onngay_tao_phieuChanging(System.DateTime value);
    partial void Onngay_tao_phieuChanged();
    #endregion
		
		public PhieuNhap()
		{
			this._ChiTietPhieuNhaps = new EntitySet<ChiTietPhieuNhap>(new Action<ChiTietPhieuNhap>(this.attach_ChiTietPhieuNhaps), new Action<ChiTietPhieuNhap>(this.detach_ChiTietPhieuNhaps));
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nha_cung_cap", DbType="Int NOT NULL")]
		public int id_nha_cung_cap
		{
			get
			{
				return this._id_nha_cung_cap;
			}
			set
			{
				if ((this._id_nha_cung_cap != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nha_cung_capChanging(value);
					this.SendPropertyChanging();
					this._id_nha_cung_cap = value;
					this.SendPropertyChanged("id_nha_cung_cap");
					this.Onid_nha_cung_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao_phieu", DbType="Date NOT NULL")]
		public System.DateTime ngay_tao_phieu
		{
			get
			{
				return this._ngay_tao_phieu;
			}
			set
			{
				if ((this._ngay_tao_phieu != value))
				{
					this.Onngay_tao_phieuChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao_phieu = value;
					this.SendPropertyChanged("ngay_tao_phieu");
					this.Onngay_tao_phieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_ChiTietPhieuNhap", Storage="_ChiTietPhieuNhaps", ThisKey="id", OtherKey="id_phieu_nhap")]
		public EntitySet<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this._ChiTietPhieuNhaps;
			}
			set
			{
				this._ChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_PhieuNhap", Storage="_NhaCungCap", ThisKey="id_nha_cung_cap", OtherKey="id", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.PhieuNhaps.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.PhieuNhaps.Add(this);
						this._id_nha_cung_cap = value.id;
					}
					else
					{
						this._id_nha_cung_cap = default(int);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = this;
		}
		
		private void detach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _mo_ta;
		
		private string _hinh_anh;
		
		private System.Nullable<int> _id_thuong_hieu;
		
		private EntitySet<BienTheSanPham> _BienTheSanPhams;
		
		private EntityRef<ThuongHieu> _ThuongHieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Onid_thuong_hieuChanging(System.Nullable<int> value);
    partial void Onid_thuong_hieuChanged();
    #endregion
		
		public SanPham()
		{
			this._BienTheSanPhams = new EntitySet<BienTheSanPham>(new Action<BienTheSanPham>(this.attach_BienTheSanPhams), new Action<BienTheSanPham>(this.detach_BienTheSanPhams));
			this._ThuongHieu = default(EntityRef<ThuongHieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(1000)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="VarChar(300)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuong_hieu", DbType="Int")]
		public System.Nullable<int> id_thuong_hieu
		{
			get
			{
				return this._id_thuong_hieu;
			}
			set
			{
				if ((this._id_thuong_hieu != value))
				{
					if (this._ThuongHieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_thuong_hieuChanging(value);
					this.SendPropertyChanging();
					this._id_thuong_hieu = value;
					this.SendPropertyChanged("id_thuong_hieu");
					this.Onid_thuong_hieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_BienTheSanPham", Storage="_BienTheSanPhams", ThisKey="id", OtherKey="id_san_pham")]
		public EntitySet<BienTheSanPham> BienTheSanPhams
		{
			get
			{
				return this._BienTheSanPhams;
			}
			set
			{
				this._BienTheSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuongHieu_SanPham", Storage="_ThuongHieu", ThisKey="id_thuong_hieu", OtherKey="id", IsForeignKey=true)]
		public ThuongHieu ThuongHieu
		{
			get
			{
				return this._ThuongHieu.Entity;
			}
			set
			{
				ThuongHieu previousValue = this._ThuongHieu.Entity;
				if (((previousValue != value) 
							|| (this._ThuongHieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuongHieu.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._ThuongHieu.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._id_thuong_hieu = value.id;
					}
					else
					{
						this._id_thuong_hieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThuongHieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BienTheSanPhams(BienTheSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_BienTheSanPhams(BienTheSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPhamTonKho")]
	public partial class SanPhamTonKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_bien_the_san_pham;
		
		private int _id_kho;
		
		private int _so_luong;
		
		private EntityRef<BienTheSanPham> _BienTheSanPham;
		
		private EntityRef<Kho> _Kho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_bien_the_san_phamChanging(int value);
    partial void Onid_bien_the_san_phamChanged();
    partial void Onid_khoChanging(int value);
    partial void Onid_khoChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    #endregion
		
		public SanPhamTonKho()
		{
			this._BienTheSanPham = default(EntityRef<BienTheSanPham>);
			this._Kho = default(EntityRef<Kho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_bien_the_san_pham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_bien_the_san_pham
		{
			get
			{
				return this._id_bien_the_san_pham;
			}
			set
			{
				if ((this._id_bien_the_san_pham != value))
				{
					if (this._BienTheSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_bien_the_san_phamChanging(value);
					this.SendPropertyChanging();
					this._id_bien_the_san_pham = value;
					this.SendPropertyChanged("id_bien_the_san_pham");
					this.Onid_bien_the_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_kho
		{
			get
			{
				return this._id_kho;
			}
			set
			{
				if ((this._id_kho != value))
				{
					if (this._Kho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khoChanging(value);
					this.SendPropertyChanging();
					this._id_kho = value;
					this.SendPropertyChanged("id_kho");
					this.Onid_khoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BienTheSanPham_SanPhamTonKho", Storage="_BienTheSanPham", ThisKey="id_bien_the_san_pham", OtherKey="id", IsForeignKey=true)]
		public BienTheSanPham BienTheSanPham
		{
			get
			{
				return this._BienTheSanPham.Entity;
			}
			set
			{
				BienTheSanPham previousValue = this._BienTheSanPham.Entity;
				if (((previousValue != value) 
							|| (this._BienTheSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BienTheSanPham.Entity = null;
						previousValue.SanPhamTonKhos.Remove(this);
					}
					this._BienTheSanPham.Entity = value;
					if ((value != null))
					{
						value.SanPhamTonKhos.Add(this);
						this._id_bien_the_san_pham = value.id;
					}
					else
					{
						this._id_bien_the_san_pham = default(int);
					}
					this.SendPropertyChanged("BienTheSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_SanPhamTonKho", Storage="_Kho", ThisKey="id_kho", OtherKey="id", IsForeignKey=true)]
		public Kho Kho
		{
			get
			{
				return this._Kho.Entity;
			}
			set
			{
				Kho previousValue = this._Kho.Entity;
				if (((previousValue != value) 
							|| (this._Kho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kho.Entity = null;
						previousValue.SanPhamTonKhos.Remove(this);
					}
					this._Kho.Entity = value;
					if ((value != null))
					{
						value.SanPhamTonKhos.Add(this);
						this._id_kho = value.id;
					}
					else
					{
						this._id_kho = default(int);
					}
					this.SendPropertyChanged("Kho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongSoSanPham")]
	public partial class ThongSoSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ram;
		
		private string _dung_luong;
		
		private string _mau_sac;
		
		private EntitySet<BienTheSanPham> _BienTheSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnramChanging(string value);
    partial void OnramChanged();
    partial void Ondung_luongChanging(string value);
    partial void Ondung_luongChanged();
    partial void Onmau_sacChanging(string value);
    partial void Onmau_sacChanged();
    #endregion
		
		public ThongSoSanPham()
		{
			this._BienTheSanPhams = new EntitySet<BienTheSanPham>(new Action<BienTheSanPham>(this.attach_BienTheSanPhams), new Action<BienTheSanPham>(this.detach_BienTheSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ram", DbType="VarChar(300)")]
		public string ram
		{
			get
			{
				return this._ram;
			}
			set
			{
				if ((this._ram != value))
				{
					this.OnramChanging(value);
					this.SendPropertyChanging();
					this._ram = value;
					this.SendPropertyChanged("ram");
					this.OnramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dung_luong", DbType="NVarChar(300)")]
		public string dung_luong
		{
			get
			{
				return this._dung_luong;
			}
			set
			{
				if ((this._dung_luong != value))
				{
					this.Ondung_luongChanging(value);
					this.SendPropertyChanging();
					this._dung_luong = value;
					this.SendPropertyChanged("dung_luong");
					this.Ondung_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mau_sac", DbType="NVarChar(300)")]
		public string mau_sac
		{
			get
			{
				return this._mau_sac;
			}
			set
			{
				if ((this._mau_sac != value))
				{
					this.Onmau_sacChanging(value);
					this.SendPropertyChanging();
					this._mau_sac = value;
					this.SendPropertyChanged("mau_sac");
					this.Onmau_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongSoSanPham_BienTheSanPham", Storage="_BienTheSanPhams", ThisKey="id", OtherKey="id_thong_so_san_pham")]
		public EntitySet<BienTheSanPham> BienTheSanPhams
		{
			get
			{
				return this._BienTheSanPhams;
			}
			set
			{
				this._BienTheSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BienTheSanPhams(BienTheSanPham entity)
		{
			this.SendPropertyChanging();
			entity.ThongSoSanPham = this;
		}
		
		private void detach_BienTheSanPhams(BienTheSanPham entity)
		{
			this.SendPropertyChanging();
			entity.ThongSoSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuongHieu")]
	public partial class ThuongHieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _hinh_anh;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    #endregion
		
		public ThuongHieu()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="VarChar(300)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuongHieu_SanPham", Storage="_SanPhams", ThisKey="id", OtherKey="id_thuong_hieu")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.ThuongHieu = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.ThuongHieu = null;
		}
	}
}
#pragma warning restore 1591
